mappings:
- deprecatedAPI: 
    group: extensions
    version: v1beta1
    kind: Deployment
  newAPI:
    group: apps
    version: v1
    kind: Deployment
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: apps
    version: v1beta1
    kind: Deployment
  newAPI: 
    group: apps
    version: v1
    kind: Deployment
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: apps
    version: v1beta2
    kind: Deployment
  newAPI: 
    group: apps
    version: v1
    kind: Deployment
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: apps
    version: v1beta1
    kind: StatefulSet
  newAPI: 
    group: apps
    version: v1
    kind: StatefulSet
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: apps
    version: v1beta2
    kind: StatefulSet
  newAPI: 
    group: apps
    version: v1
    kind: StatefulSet
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: extensions
    version: v1beta1
    kind: DaemonSet
  newAPI: 
    group: apps
    version: v1
    kind: DaemonSet
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: apps
    version: v1beta2
    kind: DaemonSet
  newAPI: 
    group: apps
    version: v1
    kind: DaemonSet
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: extensions
    version: v1beta1
    kind: ReplicaSet
  newAPI: 
    group: apps
    version: v1
    kind: ReplicaSet
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: apps
    version: v1beta1
    kind: ReplicaSet
  newAPI: 
    group: apps
    version: v1
    kind: ReplicaSet
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: apps
    version: v1beta2
    kind: ReplicaSet
  newAPI: 
    group: apps
    version: v1
    kind: ReplicaSet
  deprecatedInVersion: "v1.9"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: extensions
    version: v1beta1
    kind: NetworkPolicy
  newAPI: 
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
  deprecatedInVersion: "v1.8"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: extensions
    version: v1beta1
    kind: PodSecurityPolicy
  newAPI: 
    group: policy
    version: v1beta1
    kind: PodSecurityPolicy
  deprecatedInVersion: "v1.10"
  removedInVersion: "v1.16"
- deprecatedAPI: 
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: MutatingWebhookConfiguration
  newAPI: 
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
  deprecatedInVersion: "v1.16"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
  newAPI: 
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
  deprecatedInVersion: "v1.16"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: apiextensions.k8s.io
    version: v1beta1
    kind: CustomResourceDefinition
  newAPI: 
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  deprecatedInVersion: "v1.16"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: apiregistration.k8s.io
    version: v1beta1
    kind: APIService
  newAPI: 
    group: apiregistration.k8s.io
    version: v1
    kind: APIService
  deprecatedInVersion: "v1.19"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: apiregistration.k8s.io
    version: v1beta1
    kind: APIServiceList
  newAPI: 
    group: apiregistration.k8s.io
    version: v1
    kind: APIServiceList
  deprecatedInVersion: "v1.19"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: authentication.k8s.io
    version: v1beta1
    kind: TokenReview
  newAPI: 
    group: authentication.k8s.io
    version: v1
    kind: TokenReview
  deprecatedInVersion: "v1.16"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: authorization.k8s.io
    version: v1beta1
    kind: LocalSubjectAccessReview
  newAPI: 
    group: authorization.k8s.io
    version: v1
    kind: LocalSubjectAccessReview
  deprecatedInVersion: "v1.16"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: authorization.k8s.io
    version: v1beta1
    kind: SelfSubjectAccessReview
  newAPI: 
    group: authorization.k8s.io
    version: v1
    kind: SelfSubjectAccessReview
  deprecatedInVersion: "v1.16"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: authorization.k8s.io
    version: v1beta1
    kind: SubjectAccessReview
  newAPI: 
    group: authorization.k8s.io
    version: v1
    kind: SubjectAccessReview
  deprecatedInVersion: "v1.16"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: certificates.k8s.io
    version: v1beta1
    kind: CertificateSigningRequest
  newAPI: 
    group: certificates.k8s.io
    version: v1
    kind: CertificateSigningRequest
  deprecatedInVersion: "v1.19"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: coordination.k8s.io
    version: v1beta1
    kind: Lease
  newAPI: 
    group: coordination.k8s.io
    version: v1
    kind: Lease
  deprecatedInVersion: "v1.14"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: extensions
    version: v1beta1
    kind: Ingress
  newAPI: 
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
  deprecatedInVersion: "v1.14"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
  newAPI: 
    group: networking.k8s.io
    version: v1
    kind: Ingress
  deprecatedInVersion: "v1.19"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: networking.k8s.io
    version: v1beta1
    kind: IngressClass
  newAPI: 
    group: networking.k8s.io
    version: v1
    kind: IngressClass
  deprecatedInVersion: "v1.19"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1alpha1
    kind: ClusterRole
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1alpha1
    kind: ClusterRoleList
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleList
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1alpha1
    kind: ClusterRoleBinding
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1alpha1
    kind: ClusterRoleBindingList
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBindingList
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1alpha1
    kind: Role
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1alpha1
    kind: RoleList
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleList
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1alpha1
    kind: RoleBinding
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1alpha1
    kind: RoleBindingList
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBindingList
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleList
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleList
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBindingList
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBindingList
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: Role
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: RoleList
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleList
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: RoleBinding
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: RoleBindingList
  newAPI: 
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBindingList
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: scheduling.k8s.io
    version: v1beta1
    kind: PriorityClass
  newAPI: 
    group: scheduling.k8s.io
    version: v1
    kind: PriorityClass
  deprecatedInVersion: "v1.14"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: storage.k8s.io
    version: v1beta1
    kind: CSIDriver
  newAPI: 
    group: storage.k8s.io
    version: v1
    kind: CSIDriver
  deprecatedInVersion: "v1.19"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: storage.k8s.io
    version: v1beta1
    kind: CSINode
  newAPI: 
    group: storage.k8s.io
    version: v1
    kind: CSINode
  deprecatedInVersion: "v1.17"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: storage.k8s.io
    version: v1beta1
    kind: StorageClass
  newAPI: 
    group: storage.k8s.io
    version: v1
    kind: StorageClass
  deprecatedInVersion: "v1.16"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: storage.k8s.io
    version: v1beta1
    kind: VolumeAttachment
  newAPI: 
    group: storage.k8s.io
    version: v1
    kind: VolumeAttachment
  deprecatedInVersion: "v1.13"
  removedInVersion: "v1.22"
- deprecatedAPI: 
    group: autoscaling
    version: v2beta1
    kind: HorizontalPodAutoscaler
  newAPI: 
    group: autoscaling
    version: v2
    kind: HorizontalPodAutoscaler
  deprecatedInVersion: "v1.23"
  removedInVersion: "v1.25"
- deprecatedAPI: 
    group: policy
    version: v1beta1
    kind: PodDisruptionBudget
  newAPI: 
    group: policy
    version: v1
    kind: PodDisruptionBudget
  deprecatedInVersion: "v1.21"
  removedInVersion: "v1.25"
- deprecatedAPI: 
    group: policy
    version: v1beta1
    kind: PodSecurityPolicy
  deprecatedInVersion: "v1.21"
  removedInVersion: "v1.25"
